apiVersion: stash.appscode.com/v1alpha2
kind: BackupConfiguration
metadata:
  name: backup-database-demo
  namespace: demo
spec:
  schedule: '@every 1h'
  # repository refers to the Repository crd that hold backend information
  backupRepository:
    name: stash-backup-repo
  # retentionPolicies specify the policy to follow to clean old backup snapshots
  retentionPolicy:
    keepLast: 5
    prune: true
